out_dir: './out_mode_canada_test'
device: 'cuda'
tb_out: './out'
# user_feature_dim: 10
# item_feature_dim: 10
# price_feature_dim: 10
# user_price_feature_dim: 10
num_items: 4
num_users: 100
# model specification
var_variation_dict:  # put empty line to indicate None.
  u: 'item' 
  i: 'constant'
var_num_params_dict:
  u: 64
  i: 128
# training
max_epochs: 10000
param_norm_eps: 0.001  # for assessing the convergence of parameter.
learning_rate: 0.0001
lr_decay: 1  # exponential learning rate decay, put 1.0 for not decaying.
eval_epoch: 100
shuffle: True  # weather to shuffle dataset.
# learning_rate: 0.3
batch_size: -1 # set to -1 to use full-batch.