site_name: Bayesian Embedding (BEMB)
site_url: https://example.com/
docs_dir: docs_src
site_dir: docs
nav:
    - Home: index.md
    - About: intro.md
    - Documentation for Torch-Choice: https://gsbdbi.github.io/torch-choice/
    - Tutorial for Data Management: https://gsbdbi.github.io/torch-choice/data_management/
    - Tutorial for Easy Data Management and Stata Users: https://gsbdbi.github.io/torch-choice/easy_data_management/
    - Tutorial for Bayesian Embedding (BEMB): bemb.md
    - Tutorial for BEMB obs2prior feature: bemb_obs2prior_simulation.md
    - Related Projects: projects.md
    - Compatibility Tests: test.md
    - API Reference BEMB: api_bemb.md

# theme: readthedocs
theme:
    name: material
    custom_dir: docs_src/overrides
    icon:
        logo: stanford/stanford

plugins:
    - search
    - mkdocstrings

markdown_extensions:
#   - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs_src/overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
