site_name: Deep Choice
site_url: https://example.com/
nav:
    - Home: index.md
    - About: intro.md
    - Get Started: install.md
    - Tutorial for  Data Management: data_management.md
    - Tutorial for Conditional Logit Model: conditional_logit_model_mode_canada.md
    - Tutorial for Nested Logit Model: nested_logit_model_house_cooling.md
    - Tutorial for Bayesian Embedding (BEMB): bemb.md
    - Related Projects: projects.md
    - Compability Tests: test.md
    - API Reference Torch-Choice: api_torch_choice.md
    - API Reference BEMB: api_bemb.md

# theme: readthedocs
theme: material
plugins:
    - search
    - mkdocstrings
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
