device: cuda
data_dir: /home/tianyudu/Data/MoreSupermarket/tsv/
out_dir: ./output/
# model configuration.
latent_dim: 10
latent_dim_price: -1
obs2prior_dict:
  # lambda_item: False
  theta_user: True
  alpha_item: True
  # zeta_user: False
  # lota_item: False
  # gamma_user: True
  # beta_item: True
#### optimization.
trace_log_q: False
shuffle: False
batch_size: 100000
num_epochs: 1000
num_mc_seeds: 1