device: cuda
data_dir: /home/tianyudu/Data/MoreSupermarket/tsv/
# data_dir: /home/tianyudu/Data/MoreSupermarket/20180101-20191231_13/tsv/
# utility: lambda_item + theta_user * alpha_item + zeta_user * item_obs
utility: lambda_item + theta_user * alpha_item + gamma_user * beta_item * price_obs
out_dir: ./output/
# model configuration.
obs2prior_dict:
  lambda_item: False
  theta_user: False
  alpha_item: False
  # zeta_user: False
  # lota_item: False
  gamma_user: False
  beta_item: False
coef_dim_dict:
  lambda_item: 1
  theta_user: 3
  alpha_item: 3
  gamma_user: 3
  beta_item: 3
#### optimization.
trace_log_q: False
shuffle: True
batch_size: 50000
num_epochs: 100
num_mc_seeds: 1