device: cuda
out_dir: ./psid_output/
# model configuration.
latent_dim: 40
latent_dim_price: -1
obs2prior_dict:
  # lambda_item: False
  theta_user: False
  alpha_item: False
  # zeta_user: False
  # lota_item: False
  # gamma_user: True
  # beta_item: True
#### optimization.
trace_log_q: False
shuffle: True
batch_size: 5000
num_epochs: 2000
num_mc_seeds: 1