out_dir: './mnist_out/'
device: 'cuda'
tb_out: './out'
# file system
base_path: '/oak/stanford/groups/athey/MoreSupermarkets/csv/new_data/nf_runs'
# stores: '3014_availability'
# stores: '3014-3098-3089-3168'
stores: '1904-1887/20180101-20191231_8/tsv'
num_items: 10
num_users: 1
# model specification
var_variation_dict:  # put empty line to indicate None.
  u: 
  i:
  ui:
  t: 'item2'
  ut:
  it:
  uit:
  intercept:
var_num_params_dict:
  u:
  i:
  ui:
  t: 784
  ut:
  it:
  uit:
  intercept:
# training
max_epochs: 100
param_norm_eps: 0.00001  # for assessing the convergence of parameter.
learning_rate: 0.0001
lr_decay: 1  # exponential learning rate decay, put 1.0 for not decaying.
eval_epoch: 1
batch_size: -1  # set to -1 to use full-batch.