data_dir: '/home/ubuntu/MoreSupermarkets_data/csv/new_data/nf_runs/1904-1887/20180101-20191231_13/tsv/grid_rand/tsv_c-100_u-1000_d-1000'
device: cuda
out_dir: '/home/ubuntu/MoreSupermarkets_data/csv/new_data/nf_runs/1904-1887/20180101-20191231_13/tsv/grid_rand/tsv_c-100_u-1000_d-1000/output'
# model configuration.
latent_dim: 10
latent_dim_price: 10
obs2prior_dict:
  # lambda_item: False
  theta_user: False
  alpha_item: False
  # zeta_user: False
  # lota_item: False
  # gamma_user: True
  # beta_item: True
#### optimization.
trace_log_q: False
shuffle: False
batch_size: 10000
num_epochs: 800
num_mc_seeds: 1
num_verify_val : 20
write_best_model : True
early_stopping:
  validation_llh_flat: 1
