device: cuda
out_dir: ./NestedBEMB_output/
# model configuration.
latent_dim_item: 3
latent_dim_category: 2
latent_dim_price: -1
obs2prior_dict_item:
  # lambda_item: False
  theta_user: False
  alpha_item: False
  # zeta_user: False
  # lota_item: False
  # gamma_user: True
obs2prior_dict_category:
  # lambda_item: False
  theta_user: False
  alpha_item: False
  # zeta_user: False
  # lota_item: False
  # gamma_user: True
  # beta_item: True # beta_item: True
#### optimization.
trace_log_q: False
shuffle: False
batch_size: 10000
num_epochs: 100
num_mc_seeds: 1