# This is a basic workflow to help you get started with Actions

name: build-makrdown-website

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the documentation source.
  push:
    paths: 'docs_src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install mkdocs and plugins.
        run: |
          pip install mkdocs
          pip install mkdocstrings
          pip install mkdocs-material

      - name: run mkdocs build to generate html files.
        run: mkdocs build
        
